### ISSUE TITLE
Use GitPod tools to configure JCASC

### ISSUE THREAD

**Issue by gounthar** [ash-sxn/GSoC-2023-docker-based-quickstart#119]
From @dduportal:

Note for later improvements (e.g. not priority and nice to have, not mandatory at all): https://www.gitpod.io/docs/configure/workspaces/ports#accessing-port-urls states that you can use the [`gh port`](https://www.gitpod.io/docs/references/gitpod-cli#url) command to programmaticaly retrieve the exposed URL.

With a JCasc configured to set up the Jenkins URL from an environment variable passed by docker, you can think about an automatic setup in the case of GitPod (`commands in the `.gitpod.yml`)

```
# In the gitpod yaml
export JENKINS_EXT_URL="$(gp port 8080)"

# Everywhere: laptops, gitpods, etc.
docker compose up --detach --build --force-recreate
```

with something like this:

```yaml
# docker-compose.yml
services:
  jenkins:
    # ...
    environment:
      - JENKINS_EXT_URL=${JENKINS_EXT_URL:-http://localhost:8080} # Default to localhost:8080 with HTTP
# ...
```

and

```yaml
# JCasc
# ...
unclassified:
  location:
    url: "${JENKINS_EXT_URL}"
```
