### ISSUE TITLE
`open-browser` not working as intended 

### ISSUE THREAD

**Issue by ash-sxn** [ash-sxn/GSoC-2023-docker-based-quickstart#166]
```yaml
ports:
  - name: Jenkins controller
    port: 8080
    protocol: http
    onOpen: open-browser
    description: The Jenkins Controller to use for the tutorials
```
This part of the gitpod.yml file is not working properly,  as it sometimes opens the browser but sometimes it doesn't for some(unknow) reason, and it also stops the popup that used to come before that leads to Jenkins UI,
